### ISSUE TITLE
Use Hack Club's design system

### ISSUE THREAD

**Issue by ifvictr** [hackchicago/hackchicago#27]
Just thought I'd bring this up--it's been at the back of my mind for awhile now. Since this event is Hack Club-related, I feel like its site should use the system which people already associate with Hack Club itself.

Requesting thoughts/comments!

**Comment by itsmingjie** [comment]
So I'd love to have it under DS but here's the problem... The current site is written statically, and there's not a current deviation of DS for static sites. It would also take a lot of extra effort to rewrite the site, since a lot of our current components would need to be completely rewritten in react.

My best suggestion would be to modify the design of the site so that it can get as close as the design elements of DS. Also refer to #21 about how our current design is inconsistent - that should also be fixed by converting the design.

**Comment by ifvictr** [comment]
Nonetheless, I'd be down to help rewrite it in React. But that'd work also!

**Comment by zanedb** [comment]
I think for the purposes of this hackathon a standard site will suffice. Sure, we could rewrite in React, but in terms of time constraints (and experience level of our team) our current approach is best.
